# Generated by Django 4.2.7 on 2023-11-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('aluno', '0001_initial'),
        ('disciplina', '0001_initial'),
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina', verbose_name='Disciplina')),
                ('membro01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro01_tcc_set', to='professor.professor', verbose_name='Presidente da Banca:')),
                ('membro02', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='membro02_tcc_set', to='professor.professor', verbose_name='Membro 01:')),
                ('membro03', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='membro03_tcc_set', to='professor.professor', verbose_name='Menbro 02:')),
                ('nomeAluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomeAluno_tcc_set', to='aluno.aluno', verbose_name='Aluno:')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador_tcc_set', to='professor.professor', verbose_name='Orientador:')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodo.periodo', verbose_name='Periodo')),
                ('tituloTCC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tituloTCC_tcc_set', to='aluno.aluno', verbose_name='Titulo do TCC:')),
            ],
        ),
    ]
