# Generated by Django 4.2.7 on 2023-11-26 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('tcc', '0003_remove_tcc_nomealuno_tcc_aluno_alter_tcc_membro01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tccs', to='aluno.aluno', verbose_name='Aluno'),
        ),
    ]
