# Generated by Django 4.2.7 on 2023-11-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0007_tcc_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcc',
            name='tituloTCC',
        ),
    ]
