# Generated by Django 4.2.7 on 2023-11-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_remove_aluno_titulotcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='tituloTCC',
            field=models.CharField(max_length=250, null=True, verbose_name='Titulo do Trabalho:'),
        ),
    ]
